# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
cache: pip

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.5
      env: TOXENV=flake8
    - python: 3.5
      env: TOXENV=docs-linkcheck
    - python: 3.4
      env: TOXENV=py34
    - python: 3.3
      env: TOXENV=py33
    - python: 2.7
      env: TOXENV=py27
    - python: 2.6
      env: TOXENV=py26

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip --cache-dir $HOME/.cache/pip install -r requirements_dev.txt

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: waynr
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: waynr/access
    condition: $TOXENV == py35
